//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace EmployeeData.Database
{

    [Persistent(@"employees")]
    public partial class Employees : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        [ColumnDbDefaultValue("nextval('employees_id_seq'::regclass)")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fFirstName;
        [Size(50)]
        [Persistent(@"first_name")]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fLastName;
        [Size(50)]
        [Persistent(@"last_name")]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fEmail;
        [Indexed(Name = @"employees_email_key", Unique = true)]
        [Persistent(@"email")]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        int fSalary;
        [Persistent(@"salary")]
        public int Salary
        {
            get { return fSalary; }
            set { SetPropertyValue<int>(nameof(Salary), ref fSalary, value); }
        }
    }

}
