//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace EmployeeData.Database
{

    [Persistent(@"softwaredeveloper")]
    public partial class Softwaredeveloper : XPLiteObject
    {
        int fId;
        [Key]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fFirstname;
        [Size(50)]
        [Persistent(@"firstname")]
        public string Firstname
        {
            get { return fFirstname; }
            set { SetPropertyValue<string>(nameof(Firstname), ref fFirstname, value); }
        }
        string fLastname;
        [Size(50)]
        [Persistent(@"lastname")]
        public string Lastname
        {
            get { return fLastname; }
            set { SetPropertyValue<string>(nameof(Lastname), ref fLastname, value); }
        }
        string fEmail;
        [Persistent(@"email")]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fProgramminglanguage;
        [Size(50)]
        [Persistent(@"programminglanguage")]
        public string Programminglanguage
        {
            get { return fProgramminglanguage; }
            set { SetPropertyValue<string>(nameof(Programminglanguage), ref fProgramminglanguage, value); }
        }
        int fYearsofexperience;
        [Persistent(@"yearsofexperience")]
        public int Yearsofexperience
        {
            get { return fYearsofexperience; }
            set { SetPropertyValue<int>(nameof(Yearsofexperience), ref fYearsofexperience, value); }
        }
    }

}
